Avoid stale file handles in merged rootfs
Example of a the first start after a system update:

 root@mt7688:~# opkg install iperf3
 Installing iperf3 (3.2) on root.
 Downloading http://sg-low-cost-gateway-dev.s3.amazonaws.com/feeds/opkg-head/mips32r2el-24kc-nf/iperf3_3.2-r0_mips32r2el-24kc-nf.ipk.
 Configuring iperf3.
 /sbin/ldconfig: Renaming of /etc/ld.so.cache~ to /etc/ld.so.cache failed: Stale file handle
 Collected errors:
  * pkg_run_script: package "iperf3" postinst script returned status 1.
  * opkg_configure: iperf3.postinst returned 1.
 ERROR: 255 | root@mt7688:~# mount / -o remount
 root@mt7688:~# opkg install iperf3
 Package iperf3 (3.2-r0) installed in root is up to date.
 Configuring iperf3.