healthcheck: Improve output on error
This improves the output in case the communication to the RM does not
work.

Instead of an empty data field:

```
OK: [network_key_sgse_1024] result=0, data: omitted
Terminated
ERROR: [lb_radio_gateway_api] result=1, data:
Terminated
ERROR: [lb_radio_driver_state] result=2, data:
```

We do now get this:

```
OK: [network_key_sgse_1024] result=0, data: omitted
Terminated
ERROR: [lb_radio_gateway_api] result=1, data: undetermined
Terminated
ERROR: [lb_radio_driver_state] result=2, data: undetermined
```

Issue: SG-21036